spring:

  kafka:
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9093
#    bootstrap-servers: lassb-service01.si.edu:9092,lassb-service02.si.edu:9092,lassb-service03.si.edu:9092
    consumer:
      client-id: nutch-boot-kafka-consumer
      group-id: nutch-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 5000
    listener:
      type: batch

nutch:
  kafka:
    topic-name: nutch
    output-dir: output

camel:
  component:
    kafka:
      brokers: ${spring.kafka.bootstrap-servers}
      client-id: ${spring.kafka.consumer.client-id}
      group-id: ${spring.kafka.consumer.group-id}
      auto-offset-reset: ${spring.kafka.consumer.auto-offset-reset}
      key-serializer: ${spring.kafka.consumer.key-deserializer}
      value-deserializer: ${spring.kafka.consumer.value-deserializer}
      max-poll-records: ${spring.kafka.consumer.max-poll-records}
  batch:
    completion:
      timeout: 30000