version: "3.9"

services:

  nutch-hadoop:
    container_name: ossearch-nutch-hadoop
    image: ossearch-nutch-hadoop
    build:
      context: ./
      dockerfile: ./Dockerfile-nutch-hadoop
      args:
        NUTCH_VERSION: 1.18
        HADOOP_VERSION: 3.2.2
    restart: always
    depends_on:
      - solr
    ports:
      - 8088:8088
      - 9870:9870
      - 19888:19888
      - 8042:8042
      - 8188:8188
      - 9868:9868
      - 9864:9864
      - 10002:10002
    networks:
      - ossearch

  solr:
    container_name: ossearch-solr-hadoop
    image: ossearch-solr-hadoop
    command: bash -c "precreate-core external-v1 /ossearch-config; exec solr -f"
    build:
      context: ./solr
      dockerfile: ./Dockerfile-solr
    restart: always
    ports:
      - 8984:8983
    networks:
      - ossearch

# container networks
networks:
  ossearch: