spring:
  application:
    name: ossearch-crawler
  profiles:
    active: test

  security:
    user:
      name: xxxxxxxxx
      password: xxxxxxxxx

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jmx:
    enabled: true

  jackson:
    serialization:
      indent_output: true
      fail-on-empty-beans: false

  output:
    ansi:
      enabled: always

  main:
    allow-bean-definition-overriding: true

  data:
    rest:
      default-page-size: 10
      enable-enum-translation: false
      base-path: api
    solr:
      host: xxxxxxxxx
      slave: xxxxxxxxx
      collection: xxxxxxxxx
      # Max number of Row's to return per solr query
      max-rows:  1000
      # Max number of Docs's per solr add
      max-docs: 100000
      commit-within: 300000
      upload-enabled: false
      repositories:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxxxx:xxxxxxxxx/si_search_db_v2?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      max-lifetime: 60000
      connection-timeout: 300000
      idle-timeout: 120000
      leak-detection-threshold: 300000

  # JPA drop and recreate tables, show sql in logs
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        generate_statistics: true
#        order_inserts: true
        jdbc:
          batch_size: 5000
    open-in-view: false

  quartz:
    auto-startup: true
    startup-delay: 30
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    jdbc:
      platform: mysql
      initialize-schema: never

  ldap:
    urls: ldap://xxxxxxxxx
    port: 389
    base: xxxxxxxxx
    username: xxxxxxxxx
    password: xxxxxxxxx
    embedded:
      enabled: false

  boot:
    admin:
      client:
        enabled: false
        url: http://localhost:8484/admin
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          name: ${spring.application.name}
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
      context-path: /admin

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    logfile:
      external-file: logs/${spring.application.name}.log
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      include: REQUEST_HEADERS,RESPONSE_HEADERS,COOKIE_HEADERS,AUTHORIZATION_HEADER,PRINCIPAL,REMOTE_ADDRESS,SESSION_ID,TIME_TAKEN

server:
  port: 8484
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password


springdoc:
  swagger-ui:
    doc-expansion: none

ossearch:
  embedded-vuejs: true
  allowedOrigins: "http://0.0.0.0:3000,http://localhost:3000,http://127.0.0.1:3000"
  jwt:
    # key used to sign JWT tokens (should be secure and long)
    secret: xxxxxxxxx
    # 3600000 ms = 60 min
    expirationMs: 3600000
    # 86400000 ms = 24 hrs
    refreshExpirationMs: 86400000
    # Purge tokens at 5am every day
    token-purge-task:
      cron:
        # At 05:00, every day
        expression: 0 0 5 * * ?
    # Refresh search fields at 5am every day
    search-meta-field-service-task:
      cron:
        # At 05:00, every day
        expression: 0 0 5 * * ?
  nutch:
    pluginsDir: plugins
    confDir: conf
    crawlDir: crawls
  edan-api:
    url: https://edandev.si.edu
    path: /metadata/v2.0/metadata/search.htm
    appId: xxxxxxxxxxxx
    appKey: xxxxxxxxxxx

logging:
  #  config: config/logback.xml
  file:
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 100
      total-size-cap: 4GB

